cSarpProject/Controllers/AccounceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using cSarpProject.Data;
using cSarpProject.Models;
// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace cSarpProject.Controllers
{
    public class AccounceController : Controller
    {
		// GET: /<controller>/


		private readonly TestContext _context;
		public AccounceController(TestContext context)
		{
			_context = context;

		}
        public IActionResult Index()
        {
			var aaa = _context.Employee.ToList();
			PhotoGallary12 cm = new PhotoGallary12{
				StudentAll12 = aaa
			};
			return View(cm);
        }

		public IActionResult Salary()
		{
			var aaa = _context.Salary.ToList();
			EClassSalary cm = new EClassSalary
			{
				SalaryF = aaa
			};
			return View(cm);
		}
		
        public IActionResult Attendence()
		{
			return View();
		}

		public IActionResult Join()
		{
			return View();
		}
       
        public IActionResult AddEmployee([Bind("Id,FirstName,LastName, PermanentAddress, PresentAddress, ContactAddress, ContactMail, ContactNo, Phone")]Employee obj1)
		{
			using (var db1 = _context)
			{

                var std1 = new Employee
				{
					Id = obj1.Id,
					FirstName = obj1.FirstName,
                    LastName = obj1.LastName,
					PermanentAddress = obj1.PermanentAddress,
                    PresentAddress = obj1.PresentAddress,
                    ContactAddress = obj1.ContactAddress,
                    ContactMail = obj1.ContactMail,
                    ContactNo = obj1.ContactNo,
                    Phone = obj1.Phone,
				};
                db1.Employee.Add(std1);
				db1.SaveChanges();
			}
			return RedirectToAction("Join");
		}






		public IActionResult Leave()
		{
			var aaa = _context.Leave.ToList();
			EClassLeave cm = new EClassLeave
			{
				LeaveF = aaa
			};
			return View(cm);
		}



		public IActionResult SaveNotice([Bind("Id,NoticeType, NoticeName,NoticeDate")]Notice obj)
		{
			using (var db1 = _context)
			{
				var std = new Notice
				{
					Id = obj.Id,
					NoticeType = obj.NoticeType,
					NoticeName = obj.NoticeName,
                    NoticeDate = obj.NoticeDate
				};
				db1.Notice.Add(std);
				db1.SaveChanges();
			}
			return RedirectToAction("Index");
		}

		public IActionResult Notice()
		{
			return View();
		}
    }
}

cSarpProject/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using cSarpProject.Data;
using cSarpProject.Models;
// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace cSarpProject.Controllers
{
    public class AdminController : Controller
    {
		// GET: /<controller>/


		private readonly TestContext _context;
		public AdminController(TestContext context)
		{
			_context = context;

		}
        public IActionResult Index()
        {
			var aaa = _context.Employee1.ToList();
			EClass cm = new EClass
			{
				StudentF = aaa
			};
			return View(cm);
        }
		public IActionResult IDCreation()
		{
			return View();
		}





		public IActionResult UpdateAdBio()
		{
			var aaa = _context.Notice.ToList();
			EClassNoticeA cm = new EClassNoticeA
			{
				NoticeFA = aaa
			};
			return View(cm);
		}
		public IActionResult Log()
		{
			return View();
		}
    }
}

cSarpProject/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using cSarpProject.Data;
using cSarpProject.Models;
// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace cSarpProject.Controllers
{
    public class TeacherController : Controller
    {
		// GET: /<controller>/


		private readonly TestContext _context;
		public TeacherController(TestContext context)
		{
			_context = context;

		}
        public IActionResult Index()
        {
			var aaa = _context.Employee.ToList();
			PhotoGallary123 cm = new PhotoGallary123
			{
				StudentAll123 = aaa
			};
			return View(cm);
        }
		public IActionResult Salary()
		{
			var aaa = _context.Salary.ToList();
			EClassSalaryT cm = new EClassSalaryT
			{
				SalaryFT = aaa
			};
			return View(cm);
		}
		public IActionResult Attendence()
		{
			return View();
		}

		public IActionResult Leave()
		{
			var aaa = _context.Leave.ToList();
			EClassLeaveT cm = new EClassLeaveT
			{
				LeaveFT = aaa
			};
			return View(cm);
		}
		public IActionResult Notice()
		{
            var aaa = _context.Notice.ToList();
			EClassNoticeT cm = new EClassNoticeT
			{
				NoticeFT = aaa
			};
			return View(cm);
		}
    }
}

cSarpProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - cSarpProject</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span><!---->
                </button>
             <!--   <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">cSarpProject</a> -->
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="PhotoGallary">Photo Gallary</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
						<!--
						 <li><a asp-area="" asp-controller="Home" asp-action="StudentsList">StudentsList</a></li>

						<li><a asp-area="" asp-controller="Home" asp-action="AddStudent">AddStudent</a></li>
						JoinList
						<li><a asp-area="" asp-controller="Home" asp-action="JoinList">JoinList</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Salary">Salary</a></li>
                        -->
						 
						 <li><a asp-area="" asp-controller="Admin" asp-action="Index">Admin</a></li>
						 <li><a asp-area="" asp-controller="Accounce" asp-action="Index">Accounce</a></li>
						<li><a asp-area="" asp-controller="Teacher" asp-action="Index">Stuff</a></li>
						
						
						
                </ul>
					<ul class="nav navbar-nav navbar-right">
      <!--<li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>-->
      <li><a href="Login.html" data-toggle="modal" data-target="#login-modal"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - cm@bdull@h</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

cSarpProject/Views/Shared/_Layout_Cm.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - cSarpProject</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span><!---->
                </button>
             <!--   <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">cSarpProject</a> -->
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>

                   <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Photo Gallary <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">Page 1-1</a></li>
          <li><a href="#">Page 1-2</a></li>
          <li><a href="#">Page 1-3</a></li>
        </ul>
      </li>
						<li><a href="#" data-toggle="modal" data-target="#login-modal">Login</a></li>




						
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - cm@bdull@h</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>




			
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
			<script  src="~/lib/bootstrap/dist/js/bootstrap-datetimepicker.js" asp-append-version="true"></script>
<script  src="~/lib/bootstrap/dist/js/bootstrap-datetimepicker.bn.js" asp-append-version="true"></script>

        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

cSarpProject/Views/Shared/_Layout_accounce.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - cSarpProject</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
			<link rel="stylesheet" href="~/lib/jquery_ui/jquery-ui.css">
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

		

</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span><!---->
                </button>
             <!--   <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">cSarpProject</a> -->
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Accounce" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Accounce" asp-action="Salary">Salary</a></li>
                    <li><a asp-area="" asp-controller="Accounce" asp-action="Attendence">Attendence</a></li>
                    <li><a asp-area="" asp-controller="Accounce" asp-action="Leave">Leave</a></li>
                    <li><a asp-area="" asp-controller="Accounce" asp-action="Join">Join</a></li>						
                    <li><a asp-area="" asp-controller="Accounce" asp-action="Notice">Notice Send</a></li>


			</ul>			
     <ul class="nav navbar-nav navbar-right">
      <!--<li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>-->
      <li><a href="Login.html" data-toggle="modal" data-target="#login-modal"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
    </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - cm@bdull@h</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>

            <!--by cm-->
  <script src="~/lib/jquery_ui/jquery-ui.js"></script>



  <script src="~/lib/bootstrap/dist//js/bootstrap.min.js"></script>
      <script src = "~/lib/jquery_ui/jquery-1.12.4.js"></script>
      <script src = "~/lib/jquery_ui/jquery-ui.js"></script>

        
  <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>

        <script>
         $(function() {
            $( "#datepicker-13" ).datepicker();
            $( "#datepicker-13" ).datepicker("show");
         });
      </script>

        
        <!--script end -->








			
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

cSarpProject/Views/Shared/_Layout_admin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - cSarpProject</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span><!---->
                </button>
             <!--   <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">cSarpProject</a> -->
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Admin" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Admin" asp-action="IDCreation">Create ID</a></li>
                   <!-- <li><a asp-area="" asp-controller="Admin" asp-action="UpdateAdBio">Update Profile</a></li>-->
                    <li><a asp-area="" asp-controller="Admin" asp-action="UpdateAdBio">Notification</a></li>
                    <li><a asp-area="" asp-controller="Admin" asp-action="Log">Log</a></li>

			</ul>			
     <ul class="nav navbar-nav navbar-right">
      <!--<li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>-->
      <li><a href="#" ><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
    </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - cm@bdull@h</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

cSarpProject/Views/Shared/_Layout_teacher.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - cSarpProject</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span><!---->
                </button>
             <!--   <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">cSarpProject</a> -->
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Accounce" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Teacher" asp-action="Salary">Salary</a></li>
                    <li><a asp-area="" asp-controller="Teacher" asp-action="Attendence">Attendence</a></li>
                    <li><a asp-area="" asp-controller="Teacher" asp-action="Leave">Leave</a></li>                      
                    <li><a asp-area="" asp-controller="Teacher" asp-action="Notice">Notification</a></li>

</ul>			
     <ul class="nav navbar-nav navbar-right">
      <!--<li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>-->
      <li><a href="Login.html" data-toggle="modal" data-target="#login-modal"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
    </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - cm@bdull@h</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>